<?php
// This script and data application were generated by AppGini 5.40
// Download AppGini for free from http://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/class_bibliography_archive.php");
	include("$currDir/class_bibliography_archive_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('class_bibliography_archive');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "class_bibliography_archive";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV=array(   
		"`class_bibliography_archive`.`id`" => "id",
		"`class_bibliography_archive`.`organization_abr`" => "organization_abr",
		"`class_bibliography_archive`.`organization`" => "organization",
		"`class_bibliography_archive`.`address_street`" => "address_street",
		"`class_bibliography_archive`.`address_place`" => "address_place",
		"`class_bibliography_archive`.`address_pc`" => "address_pc",
		"`class_bibliography_archive`.`address_region`" => "address_region",
		"`class_bibliography_archive`.`address_country`" => "address_country",
		"`class_bibliography_archive`.`phone1`" => "phone1",
		"`class_bibliography_archive`.`email1`" => "email1",
		"`class_bibliography_archive`.`web1`" => "web1"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`class_bibliography_archive`.`id`',
		2 => 2,
		3 => 3,
		4 => 4,
		5 => 5,
		6 => 6,
		7 => 7,
		8 => 8,
		9 => 9,
		10 => 10,
		11 => 11
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV=array(   
		"`class_bibliography_archive`.`id`" => "id",
		"`class_bibliography_archive`.`organization_abr`" => "organization_abr",
		"`class_bibliography_archive`.`organization`" => "organization",
		"`class_bibliography_archive`.`address_street`" => "address_street",
		"`class_bibliography_archive`.`address_place`" => "address_place",
		"`class_bibliography_archive`.`address_pc`" => "address_pc",
		"`class_bibliography_archive`.`address_region`" => "address_region",
		"`class_bibliography_archive`.`address_country`" => "address_country",
		"`class_bibliography_archive`.`phone1`" => "phone1",
		"`class_bibliography_archive`.`email1`" => "email1",
		"`class_bibliography_archive`.`web1`" => "web1"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters=array(   
		"`class_bibliography_archive`.`id`" => "ID",
		"`class_bibliography_archive`.`organization_abr`" => "Abbreviation",
		"`class_bibliography_archive`.`organization`" => "Organization name",
		"`class_bibliography_archive`.`address_street`" => "Address",
		"`class_bibliography_archive`.`address_place`" => "Place/City",
		"`class_bibliography_archive`.`address_pc`" => "Postal Code",
		"`class_bibliography_archive`.`address_region`" => "Region/Province",
		"`class_bibliography_archive`.`address_country`" => "Country",
		"`class_bibliography_archive`.`phone1`" => "Phone number",
		"`class_bibliography_archive`.`email1`" => "E-mail",
		"`class_bibliography_archive`.`web1`" => "Web"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS=array(   
		"`class_bibliography_archive`.`id`" => "id",
		"`class_bibliography_archive`.`organization_abr`" => "organization_abr",
		"`class_bibliography_archive`.`organization`" => "organization",
		"`class_bibliography_archive`.`address_street`" => "address_street",
		"`class_bibliography_archive`.`address_place`" => "address_place",
		"`class_bibliography_archive`.`address_pc`" => "address_pc",
		"`class_bibliography_archive`.`address_region`" => "address_region",
		"`class_bibliography_archive`.`address_country`" => "address_country",
		"`class_bibliography_archive`.`phone1`" => "phone1",
		"`class_bibliography_archive`.`email1`" => "email1",
		"`class_bibliography_archive`.`web1`" => "web1"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array();

	$x->QueryFrom="`class_bibliography_archive` ";
	$x->QueryWhere='';
	$x->QueryOrder='';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "class_bibliography_archive_view.php";
	$x->RedirectAfterInsert = "class_bibliography_archive_view.php?SelectedID=#ID#";
	$x->TableTitle = "Archives";
	$x->TableIcon = "table.gif";
	$x->PrimaryKey = "`class_bibliography_archive`.`id`";
	$x->DefaultSortField = '2';
	$x->DefaultSortDirection = 'asc';

	$x->ColWidth   = array(  150, 150, 150, 150, 150, 150, 150, 150, 150, 150);
	$x->ColCaption = array("Abbreviation", "Organization name", "Address", "Place/City", "Postal Code", "Region/Province", "Country", "Phone number", "E-mail", "Web");
	$x->ColFieldName = array('organization_abr', 'organization', 'address_street', 'address_place', 'address_pc', 'address_region', 'address_country', 'phone1', 'email1', 'web1');
	$x->ColNumber  = array(2, 3, 4, 5, 6, 7, 8, 9, 10, 11);

	$x->Template = 'templates/class_bibliography_archive_templateTV.html';
	$x->SelectedTemplate = 'templates/class_bibliography_archive_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `class_bibliography_archive`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='class_bibliography_archive' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `class_bibliography_archive`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='class_bibliography_archive' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`class_bibliography_archive`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: class_bibliography_archive_init
	$render=TRUE;
	if(function_exists('class_bibliography_archive_init')){
		$args=array();
		$render=class_bibliography_archive_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: class_bibliography_archive_header
	$headerCode='';
	if(function_exists('class_bibliography_archive_header')){
		$args=array();
		$headerCode=class_bibliography_archive_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: class_bibliography_archive_footer
	$footerCode='';
	if(function_exists('class_bibliography_archive_footer')){
		$args=array();
		$footerCode=class_bibliography_archive_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>