<?php
// This script and data application were generated by AppGini 5.40
// Download AppGini for free from http://bigprof.com/appgini/download/

	$currDir=dirname(__FILE__);
	include("$currDir/defaultLang.php");
	include("$currDir/language.php");
	include("$currDir/lib.php");
	@include("$currDir/hooks/storyboard.php");
	include("$currDir/storyboard_dml.php");

	// mm: can the current member access this page?
	$perm=getTablePermissions('storyboard');
	if(!$perm[0]){
		echo error_message($Translation['tableAccessDenied'], false);
		echo '<script>setTimeout("window.location=\'index.php?signOut=1\'", 2000);</script>';
		exit;
	}

	$x = new DataList;
	$x->TableName = "storyboard";

	// Fields that can be displayed in the table view
	$x->QueryFieldsTV=array(   
		"`storyboard`.`id`" => "id",
		"IF(    CHAR_LENGTH(`storylines1`.`storyline`), CONCAT_WS('',   `storylines1`.`storyline`), '') /* Scene */" => "scene",
		"`storyboard`.`shot`" => "shot"
	);
	// mapping incoming sort by requests to actual query fields
	$x->SortFields = array(   
		1 => '`storyboard`.`id`',
		2 => 2,
		3 => 3
	);

	// Fields that can be displayed in the csv file
	$x->QueryFieldsCSV=array(   
		"`storyboard`.`id`" => "id",
		"IF(    CHAR_LENGTH(`storylines1`.`storyline`), CONCAT_WS('',   `storylines1`.`storyline`), '') /* Scene */" => "scene",
		"`storyboard`.`shot`" => "shot"
	);
	// Fields that can be filtered
	$x->QueryFieldsFilters=array(   
		"`storyboard`.`id`" => "ID",
		"IF(    CHAR_LENGTH(`storylines1`.`storyline`), CONCAT_WS('',   `storylines1`.`storyline`), '') /* Scene */" => "Scene"
	);

	// Fields that can be quick searched
	$x->QueryFieldsQS=array(   
		"`storyboard`.`id`" => "id",
		"IF(    CHAR_LENGTH(`storylines1`.`storyline`), CONCAT_WS('',   `storylines1`.`storyline`), '') /* Scene */" => "scene"
	);

	// Lookup fields that can be used as filterers
	$x->filterers = array(  'scene' => 'Scene');

	$x->QueryFrom="`storyboard` LEFT JOIN `storylines` as storylines1 ON `storylines1`.`id`=`storyboard`.`scene` ";
	$x->QueryWhere='';
	$x->QueryOrder='';

	$x->AllowSelection = 1;
	$x->HideTableView = ($perm[2]==0 ? 1 : 0);
	$x->AllowDelete = $perm[4];
	$x->AllowMassDelete = false;
	$x->AllowInsert = $perm[1];
	$x->AllowUpdate = $perm[3];
	$x->SeparateDV = 1;
	$x->AllowDeleteOfParents = 0;
	$x->AllowFilters = 1;
	$x->AllowSavingFilters = 0;
	$x->AllowSorting = 1;
	$x->AllowNavigation = 1;
	$x->AllowPrinting = 1;
	$x->AllowCSV = 1;
	$x->RecordsPerPage = 10;
	$x->QuickSearch = 1;
	$x->QuickSearchText = $Translation["quick search"];
	$x->ScriptFileName = "storyboard_view.php";
	$x->RedirectAfterInsert = "storyboard_view.php?SelectedID=#ID#";
	$x->TableTitle = "Storyboard";
	$x->TableIcon = "table.gif";
	$x->PrimaryKey = "`storyboard`.`id`";

	$x->ColWidth   = array(  150, 150);
	$x->ColCaption = array("Scene", "Shot");
	$x->ColFieldName = array('scene', 'shot');
	$x->ColNumber  = array(2, 3);

	$x->Template = 'templates/storyboard_templateTV.html';
	$x->SelectedTemplate = 'templates/storyboard_templateTVS.html';
	$x->ShowTableHeader = 1;
	$x->ShowRecordSlots = 0;
	$x->HighlightColor = '#FFF0C2';

	// mm: build the query based on current member's permissions
	$DisplayRecords = $_REQUEST['DisplayRecords'];
	if(!in_array($DisplayRecords, array('user', 'group'))){ $DisplayRecords = 'all'; }
	if($perm[2]==1 || ($perm[2]>1 && $DisplayRecords=='user' && !$_REQUEST['NoFilter_x'])){ // view owner only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `storyboard`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='storyboard' and lcase(membership_userrecords.memberID)='".getLoggedMemberID()."'";
	}elseif($perm[2]==2 || ($perm[2]>2 && $DisplayRecords=='group' && !$_REQUEST['NoFilter_x'])){ // view group only
		$x->QueryFrom.=', membership_userrecords';
		$x->QueryWhere="where `storyboard`.`id`=membership_userrecords.pkValue and membership_userrecords.tableName='storyboard' and membership_userrecords.groupID='".getLoggedGroupID()."'";
	}elseif($perm[2]==3){ // view all
		// no further action
	}elseif($perm[2]==0){ // view none
		$x->QueryFields = array("Not enough permissions" => "NEP");
		$x->QueryFrom = '`storyboard`';
		$x->QueryWhere = '';
		$x->DefaultSortField = '';
	}
	// hook: storyboard_init
	$render=TRUE;
	if(function_exists('storyboard_init')){
		$args=array();
		$render=storyboard_init($x, getMemberInfo(), $args);
	}

	if($render) $x->Render();

	// hook: storyboard_header
	$headerCode='';
	if(function_exists('storyboard_header')){
		$args=array();
		$headerCode=storyboard_header($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$headerCode){
		include_once("$currDir/header.php"); 
	}else{
		ob_start(); include_once("$currDir/header.php"); $dHeader=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%HEADER%%>', $dHeader, $headerCode);
	}

	echo $x->HTML;
	// hook: storyboard_footer
	$footerCode='';
	if(function_exists('storyboard_footer')){
		$args=array();
		$footerCode=storyboard_footer($x->ContentType, getMemberInfo(), $args);
	}  
	if(!$footerCode){
		include_once("$currDir/footer.php"); 
	}else{
		ob_start(); include_once("$currDir/footer.php"); $dFooter=ob_get_contents(); ob_end_clean();
		echo str_replace('<%%FOOTER%%>', $dFooter, $footerCode);
	}
?>